import Footer from '@/components/Footer'
import Header from '@/components/Header'
import '@/styles/globals.css'

export const metadata = {
  title: 'Distribuidores de carne - Mediavilla Mark',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="relative">
      <Header/>
        {children}
        <Footer/>
        </body>
    </html>
  )
}
